apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-dnd.fullname" . }}
  namespace: {{ include "ui-dnd.namespace" . }}
  labels:
    {{- include "ui-dnd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ui-dnd.selectorLabels" . | nindent 4 }}
