{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "py-dnd.fullname" . }}
  namespace: {{ include "py-dnd.namespace" . }}
  labels:
    {{- include "py-dnd.labels" . | nindent 4 }}
spec:
  {{- if eq (.Values.replicaCount | int) 1 }}
  minAvailable: 1
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default "50%" }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "py-dnd.selectorLabels" . | nindent 6 }}
{{- end }}
