apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-sprint.fullname" . }}
  namespace: {{ include "go-sprint.namespace" . }}
  labels:
    {{- include "go-sprint.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "go-sprint.selectorLabels" . | nindent 4 }}
