{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "ttrpg-umbrella.fullname" . }}-quota
  namespace: ttrpg-{{ .Values.environment }}
  labels:
    {{- include "ttrpg-umbrella.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
