{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: {{ include "ingress.namespace" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
{{- end }}
